# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ca08919236a32102b43fd67c39254e2f36d94fe12f98888002244619a42b59bc8f3acb449934679d8db38bfa65ac2415243f392f7895bb483e6e6192894544

test:
  secret_key_base: a524dd676de7441b1794a647b6d591ce98e295912770290181b94a23dac9226dc85d5244a4f3f0e6853afe94958b3d178cdf43f6ce265340463a2cf6878b01f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
